# Generated by Django 2.2.6 on 2019-10-31 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20191031_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinstallment',
            name='expense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense', verbose_name=''),
            preserve_default=False,
        ),
    ]
