# Generated by Django 2.2.6 on 2019-10-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenseinstallment',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Pay Date'),
        ),
    ]
