# Generated by Django 2.2.6 on 2019-11-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20191031_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='expenses.Expense', verbose_name=''),
        ),
    ]
