# Generated by Django 2.2.6 on 2019-11-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20191105_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='expenses.Expense'),
        ),
    ]
