# Generated by Django 2.2.6 on 2019-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20191108_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinstallment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='expenseinstallment',
            name='transaction_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Cheque/Transaction/Card/DD number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Remarks'),
        ),
    ]
