# Generated by Django 2.2.6 on 2019-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20191112_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='transaction_no',
            field=models.CharField(default='NA', max_length=50, null=True, verbose_name='Cheque/Transaction/Card/DD number'),
        ),
    ]
