# Generated by Django 2.2.6 on 2019-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20191112_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payed',
        ),
        migrations.AddField(
            model_name='expenseinstallment',
            name='payed',
            field=models.BooleanField(choices=[('payed', 'Payed'), ('pending', 'Pending')], default=False, verbose_name='Payment status'),
        ),
    ]
