# Generated by Django 2.2.6 on 2019-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20191112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='payed',
            field=models.CharField(blank=True, choices=[('payed', 'Payment Cleared'), ('pending', 'Payment Pending')], max_length=20, verbose_name='Payment status'),
        ),
    ]
