# Generated by Django 2.2.8 on 2020-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20191112_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='expenseinstallment',
            options={'verbose_name': 'PaymentInstallment', 'verbose_name_plural': 'PaymentInstallments'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Budget', verbose_name='Loan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('corporate', 'Corporate')], max_length=50, verbose_name='Loan Type'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='Customer'),
        ),
    ]
