# Generated by Django 2.2.6 on 2019-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20191105_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vendor_photos/%Y/%m', verbose_name='upload photo'),
        ),
    ]
