# Generated by Django 2.2.6 on 2019-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='connection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Role'),
        ),
    ]
