# Generated by Django 2.2.6 on 2019-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='purpose',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('corporate', 'Corporate')], max_length=20, null=True, verbose_name='Budget Type'),
        ),
    ]
