# Generated by Django 2.2.8 on 2020-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20191105_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AddField(
            model_name='budget',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (in months)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='interest',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate of interest'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('corporate', 'Corporate')], max_length=20, null=True, verbose_name='Loan Type Type'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendor', verbose_name='Customer'),
        ),
    ]
