# Generated by Django 2.2.8 on 2020-02-02 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20200202_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Duration (in months)'),
        ),
    ]
